<?php 

	include('coneccion.php');
	include('funciones_comunes.php');
	
	if(isset($_GET['num_sem'])){
	
	$plan_dia = $_GET['fecha'];

$sql = "SELECT 
OPER_EXTRA.OPER_RUT AS RUT,CONCAT(OPER_EXTRA.OPER_NOMBRES,' ',OPER_EXTRA.OPER_PATERNO,' ',OPER_EXTRA.OPER_MATERNO) AS OPERADOR, AREA.AREA_NOMBRE AS AREA, ACT.ACTIV_NOMBRE AS ACTIVIDAD,
CMN.CMN_NOMBRE AS COMUNA, 
CASE WHEN TIPO_JEFEGRUPO = 'SUPERVISOR' THEN CONCAT(SUP.SUP_NOMBRES,' ',SUP.SUP_PATERNO,' ',SUP.SUP_MATERNO) WHEN TIPO_JEFEGRUPO = 'OPERADOR' THEN CONCAT(OPER.OPER_NOMBRES,' ',OPER.OPER_PATERNO,' ',OPER.OPER_MATERNO) ELSE '' END AS JEFE_GRUPO, ASIG.USR_NOMBRE AS ASIGNADOR,
DATE_FORMAT(PLAN.PLAN_DIA,'%d-%m-%Y') as FECHA, (ELT(WEEKDAY(PLAN.PLAN_DIA) + 1, 'LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO')) AS DIA,
PLANO.TIPO_JORNADA, PLANO.PLANO_HORAS AS HORAS, OPER_EXTRA.OPER_DIRECCION, PLAN.TIPO_JEFEGRUPO,
CASE WHEN TIPO_JEFEGRUPO = 'SUPERVISOR' THEN SUP.SUP_FONO WHEN TIPO_JEFEGRUPO = 'OPERADOR' THEN OPER.OPER_FONO ELSE '' END AS FONO_JEFEGRUPO
FROM 
PLANIFICACION_EXTRA_OPER AS PLANO
JOIN PLANIFICACION_EXTRA AS PLAN ON PLAN.PLAN_DIA = PLANO.PLAN_DIA AND PLAN.ACTIV_ID = PLANO.ACTIV_ID
JOIN SEMANAS AS SEM ON PLAN.PER_AGNO = SEM.PER_AGNO AND PLAN.SEM_NUM = SEM.SEM_NUM
LEFT JOIN SUPERVISOR AS SUP ON SUP.SUP_RUT = PLAN.SUP_RUT
LEFT JOIN OPERADOR AS OPER ON OPER.OPER_RUT = PLAN.OPER_RUT
JOIN ACTIVIDAD AS ACT ON ACT.ACTIV_ID = PLAN.ACTIV_ID
JOIN AREA AS AREA ON AREA.AREA_ID = ACT.AREA_ID
JOIN USUARIOS AS ASIG ON ASIG.USR_ID = PLAN.USR_ID
JOIN OPERADOR AS OPER_EXTRA ON OPER_EXTRA.OPER_RUT = PLANO.OPER_RUT
JOIN COMUNA AS CMN ON OPER_EXTRA.CMN_CODIGO = CMN.CMN_CODIGO
WHERE SEM.SEM_NUM =".$_GET['num_sem']." AND SEM.PER_AGNO =".$_GET['per_agno']." AND (PLAN.PLAN_DIA = '$plan_dia' or '$plan_dia' = '')
ORDER BY PLAN.PLAN_DIA ASC";

		$resultset = mysqli_query($link, $sql) or die("database error:". mysqli_error($link));
		$data = array();

		while( $rows = mysqli_fetch_assoc($resultset) ) {
		
			$data[] = 
			Array
			(
				'RUT' => $rows[RUT],
				'OPERADOR' => $rows[OPERADOR],
				'AREA' => $rows[AREA],				
				'ACTIVIDAD' => $rows[ACTIVIDAD],
				'COMUNA' => $rows[COMUNA],
				'JEFE_GRUPO' => $rows[JEFE_GRUPO],
				'ASIGNADOR' => $rows[ASIGNADOR],
				'FECHA' => $rows[FECHA],
				'DIA' => $rows[DIA],
				'TIPO_JORNADA' => $rows[TIPO_JORNADA], 
				'HORAS' => $rows[HORAS],
				'DIRECCION' => $rows[OPER_DIRECCION],
				'TIPO_JEFEGRUPO' => $rows[TIPO_JEFEGRUPO],
				'FONO_JEFEGRUPO' => $rows[FONO_JEFEGRUPO]
			);	
						
		}

		$resp = array(
		"sEcho" => 1,
		"iTotalRecords" => count($data),
		"iTotalDisplayRecords" => count($data),
		"aaData"=>$data);	
	
	}
	

	
	//Retorna respuesta
	echo json_encode($resp);
	exit();	

?>